let name=document.getElementById("name")
let age=document.getElementById("age")
let address=document.getElementById("address")
let course=document.getElementById("course")
let type=document.getElementsByName("type")
let center=document.getElementsByName("center")
let lang=document.getElementsByName("lang")